version: '3.8'

networks:
  fabric_test:
    external: true

services:
  healthscape_db:
    image: postgres
    container_name: healthscape_db
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fabric_test

  healthscape_app:
    build: .
    container_name: healthscape_app
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - /tmp/hyperledger:/tmp/hyperledger
    depends_on:
      - healthscape_db
    environment:
      PEER_ENDPOINT: ${PEER_ENDPOINT}
      CA_ENDPOINT: ${CA_ENDPOINT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://healthscape_db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      CRYPTO_PATH: ${CRYPTO_PATH}
    networks:
      - fabric_test

volumes:
  postgres-data: